version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
        environment:
          TAG: 0.1.${CIRCLE_BUILD_NUM}
          IMAGE_NAME: django-hello-world
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            python3 -m venv myenv
            source myenv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source myenv/bin/activate
            python3 manage.py test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $IMAGE_NAME:$TAG .