version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
        environment:
           IMAGE_NAME: django-hello-world
           IMAGE_REPO: mszabo2
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            python3 -m venv myenv
            source myenv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source myenv/bin/activate
            python3 manage.py test
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: Build Docker image
          command: |
            export TAG=0.1.$CIRCLE_BUILD_NUM
            echo $ACCESS_TOKEN | docker login --username mszabo2 --password-stdin
            docker build -t $IMAGE_NAME:$TAG .
      - trivy/vulnerability-scan:
          docker-image: $IMAGE_NAME:0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Push Docker image
          command: |
            export TAG=0.1.$CIRCLE_BUILD_NUM
            echo $ACCESS_TOKEN | docker login --username mszabo2 --password-stdin
            docker tag $IMAGE_NAME:$TAG $IMAGE_REPO/$IMAGE_NAME:$TAG .
            docker push $IMAGE_REPO/$IMAGE_NAME:$TAG
            
workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: docker
          
orbs: 
  trivy: signavio/trivy@1.3.0